use serde::{Deserialize, Serialize};

/// Single record in the [stations.csv](https://raw.githubusercontent.com/trainline-eu/stations/refs/heads/master/stations.csv) database.
#[derive(Debug, Serialize, Deserialize, Default, PartialEq)]
#[serde(default)]
pub struct StationRecord {
    // TODO figure out exact types for each fields
    // Where necessary, create newtypes that parse and validate the input
    pub id: i64,
    pub name: String,
    pub slug: Option<String>,
    pub uic: String,
    pub uic8_sncf: Option<String>,
    pub latitude: Option<f64>,
    pub longitude: Option<f64>,
    pub parent_station_id: Option<String>,
    pub country: Option<String>,
    pub time_zone: Option<String>,
    pub is_city: bool,
    pub is_main_station: bool,
    pub is_airport: bool,
    pub is_suggestable: bool,
    pub country_hint: bool,
    pub main_station_hint: bool,
    pub sncf_id: Option<String>,
    pub sncf_is_enabled: bool,
    pub sncf_tvs_id: Option<String>,
    pub entur_id: Option<String>,
    pub entur_is_enabled: bool,
    pub db_id: Option<String>,
    pub db_is_enabled: bool,
    pub busbud_id: Option<String>,
    pub busbud_is_enabled: bool,
    pub distribusion_id: Option<String>,
    pub distribusion_is_enabled: bool,
    pub flixbus_id: Option<String>,
    pub flixbus_is_enabled: bool,
    pub cff_id: Option<String>,
    pub cff_is_enabled: bool,
    pub leoexpress_id: Option<String>,
    pub leoexpress_is_enabled: bool,
    pub obb_id: Option<String>,
    pub obb_is_enabled: bool,
    pub ouigo_id: Option<String>,
    pub ouigo_is_enabled: bool,
    pub trenitalia_id: Option<String>,
    pub trenitalia_is_enabled: bool,
    pub trenitalia_rtvt_id: Option<String>,
    pub trenord_id: Option<String>,
    pub ntv_rtiv_id: Option<String>,
    pub ntv_id: Option<String>,
    pub ntv_is_enabled: bool,
    pub hkx_id: Option<String>,
    pub hkx_is_enabled: bool,
    pub renfe_id: Option<String>,
    pub renfe_is_enabled: bool,
    pub atoc_id: Option<String>,
    pub atoc_is_enabled: bool,
    pub benerail_id: Option<String>,
    pub benerail_is_enabled: bool,
    pub westbahn_id: Option<String>,
    pub westbahn_is_enabled: bool,
    pub sncf_self_service_machine: Option<String>,
    pub same_as: Option<String>,
    pub info_de: Option<String>,
    pub info_en: Option<String>,
    pub info_es: Option<String>,
    pub info_fr: Option<String>,
    pub info_it: Option<String>,
    pub info_nb: Option<String>,
    pub info_nl: Option<String>,
    pub info_cs: Option<String>,
    pub info_da: Option<String>,
    pub info_hu: Option<String>,
    pub info_ja: Option<String>,
    pub info_ko: Option<String>,
    pub info_pl: Option<String>,
    pub info_pt: Option<String>,
    pub info_ru: Option<String>,
    pub info_sv: Option<String>,
    pub info_tr: Option<String>,
    pub info_zh: Option<String>,
    pub normalised_code: Option<String>,
    pub iata_airport_code: Option<String>,
}
