CREATE TABLE stations (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT,
    uic TEXT NOT NULL,
    uic8_sncf TEXT,
    latitude REAL,
    longitude REAL,
    parent_station_id TEXT,
    country TEXT,
    time_zone TEXT,
    is_city BOOLEAN NOT NULL,
    is_main_station BOOLEAN NOT NULL,
    is_airport BOOLEAN NOT NULL,
    is_suggestable BOOLEAN NOT NULL,
    country_hint BOOLEAN NOT NULL,
    main_station_hint BOOLEAN NOT NULL,
    sncf_id TEXT,
    sncf_tvs_id TEXT,
    sncf_is_enabled BOOLEAN NOT NULL,
    entur_id TEXT,
    entur_is_enabled BOOLEAN NOT NULL,
    db_id TEXT,
    db_is_enabled BOOLEAN NOT NULL,
    busbud_id TEXT,
    busbud_is_enabled BOOLEAN NOT NULL,
    distribusion_id TEXT,
    distribusion_is_enabled BOOLEAN NOT NULL,
    flixbus_id TEXT,
    flixbus_is_enabled BOOLEAN NOT NULL,
    cff_id TEXT,
    cff_is_enabled BOOLEAN NOT NULL,
    leoexpress_id TEXT,
    leoexpress_is_enabled BOOLEAN NOT NULL,
    obb_id TEXT,
    obb_is_enabled BOOLEAN NOT NULL,
    trenitalia_id TEXT,
    trenitalia_is_enabled BOOLEAN NOT NULL,
    trenitalia_rtvt_id TEXT,
    trenord_id TEXT,
    ntv_rtiv_id TEXT,
    ntv_id TEXT,
    ntv_is_enabled BOOLEAN NOT NULL,
    hkx_id TEXT,
    hkx_is_enabled BOOLEAN NOT NULL,
    renfe_id TEXT,
    renfe_is_enabled BOOLEAN NOT NULL,
    atoc_id TEXT,
    atoc_is_enabled BOOLEAN NOT NULL,
    benerail_id TEXT,
    benerail_is_enabled BOOLEAN NOT NULL,
    westbahn_id TEXT,
    westbahn_is_enabled BOOLEAN NOT NULL,
    sncf_self_service_machine TEXT,
    same_as TEXT,
    info_de TEXT,
    info_en TEXT,
    info_es TEXT,
    info_fr TEXT,
    info_it TEXT,
    info_nb TEXT,
    info_nl TEXT,
    info_cs TEXT,
    info_da TEXT,
    info_hu TEXT,
    info_ja TEXT,
    info_ko TEXT,
    info_pl TEXT,
    info_pt TEXT,
    info_ru TEXT,
    info_sv TEXT,
    info_tr TEXT,
    info_zh TEXT,
    normalised_code TEXT,
    iata_airport_code TEXT
);
