name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    
    - run: ./scripts/sync-data
      shell: bash
    
    - run: docker build --tag restations .
      shell: bash
    
    - name: Smoke-test to ensure correctness
      run: |
        docker run -d -p 3000:3000 restations
        sleep 5
        # check the server runs at all
        curl --retry 5 --retry-all-errors localhost:3000/places
        # check Paris Gare de l’Est exists
        curl localhost:3000/places/8711300 | jq -e '.places.[0] | select (.name=="Paris Gare de l’Est")'
        # check Paris Gare de l’Est is found for correct location
        curl -X POST -H "Content-Type: application/json" -d '{"restrictions": {"numberOfResults": 3}, "placeInput": {"geoPosition": {"latitude": 48.877, "longitude": 2.358}}}' localhost:3000/places | jq -e '.places.[] | select (.name=="Paris Gare de l’Est")'
      shell: bash
