[package]
name = "stations-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
csv-async = { workspace = true, features = ["serde"]}
rusqlite = { workspace = true, features = ["bundled"]}
stations-core = { workspace = true }
thiserror.workspace = true
