name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  rustfmt:
    name: "Rust Format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: fmt
        run: cargo fmt --all --check

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - run: ./scripts/sync-data

      - name: clippy
        run: cargo clippy --all-targets -- -D warnings

  test:
    name: "Test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - run: ./scripts/sync-data

      - name: test
        run: cargo test

  test_docker:
    name: "Smoke-test the Docker image"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
    
      - run: ./scripts/sync-data
    
      - run: docker build --tag restations .

      - run: |
          docker run -d -p 3000:3000 restations
          sleep 3
          curl --retry 5 --retry-connrefused localhost:3000/places
