# Taken from https://github.com/mainmatter/eserde/blob/main/.github/workflows/general.yml
name: CI
on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Enforce formatting
        run: ./scripts/format

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Linting
        run: ./scripts/lint
