name: Publish Docker Image Daily

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight (UTC)
  workflow_dispatch:

jobs:
  smoke_test:
    name: "Smoke-test the Docker image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/smoke-test

  build:
    name: "Release new version to Docker Hub"
    runs-on: ubuntu-latest
    needs: smoke_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Sync data
        run: ./scripts/sync-data

      - name: Set build date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            mainmatter/restations:latest
            mainmatter/restations:${{ env.BUILD_DATE }}
